### ISSUE TITLE
afk until early October 2018

### ISSUE THREAD

**Issue by brianmorton** [brianmorton/cask-automation#11]

**Comment by brianmorton** [comment]
@vitorgalvao @commitay

I am moving from San Diego, CA (US) to Vancouver, BC (CAN) next week so I will not be contributing. 

Just a heads up.

I will be back on the 10th.

**Comment by vitorgalvao** [comment]
Thank you for the heads-up!

Have a nice… er, “moving”? “trip”? Not sure what the right word is here, but whichever it is, hope it goes without any (negative) events!

**Comment by brianmorton** [comment]
My timeline may have slipped a bit... I should be back in early October :)
